### ISSUE TITLE
CV2 resize failed

### ISSUE THREAD

**Issue by ankitbansal811** [aimagelab/human-pose-annotation-tool#2]
I am trying to run `python src/Noter.py --data_dir ./test` but this gives me the error as shown below.

```Loader started.
Loading Watch-n-patch...
Done.
20 images loaded.

Traceback (most recent call last):
  File "src/Noter.py", line 378, in <module>
    n.start(args['keep_or_skip'])
  File "src/Noter.py", line 154, in start
    new_imgs.append(cv2.resize(new_img, None, fx=0.4, fy=0.4, interpolation=cv2.INTER_CUBIC))
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize' 
```

I am using 
OS: Windows 10
Python 3.7.6
OpenCV: 4.2.0

On some google search, I could only find [this](https://stackoverflow.com/questions/31996367/opencv-resize-fails-on-large-image-with-error-215-ssize-area-0-in-funct).

**Comment by Deusy94** [comment]
Wrong path was defined for loading RGB image. 
Fixed it in my last commit.
